import os
import re
import math
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def analyze_with_groq(text: str) -> float:
    """
    Signal 1: Analyzes the text for AI-generated patterns using Groq.
    Returns a score between 0.0 (likely human) and 1.0 (likely AI).
    """
    prompt = f"""
    You are an expert stylometric and semantic analyst. 
    Analyze the following text and determine if it was written by a human or generated by an AI (like ChatGPT or Claude).
    Look for AI markers: overly formal tone, formulaic paragraph structures, words like "delve", "tapestry", "multifaceted", 
    perfectly balanced clauses, and lack of genuine personal voice or natural conversational quirks.
    Look for human markers: natural sentence length variation, informal phrasing, genuine subjective experience, mild disfluencies.
    
    Return ONLY a single float number between 0.0 and 1.0. 
    0.0 means 100% human.
    1.0 means 100% AI.
    Do not output any other text, reasoning, or formatting.
    
    Text to analyze:
    {text}
    """
    
    try:
        response = client.chat.completions.create(
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            model="llama-3.3-70b-versatile",
            temperature=0.0,
        )
        
        content = response.choices[0].message.content.strip()
        # Ensure it's a valid float
        match = re.search(r'0\.\d+|1\.0|0\.0', content)
        if match:
            score = float(match.group())
            return min(max(score, 0.0), 1.0)
        else:
            # Fallback if no valid float found
            return 0.5
    except Exception as e:
        print(f"Groq API error: {e}")
        return 0.5

def analyze_with_stylometrics(text: str) -> float:
    """
    Signal 2: Analyzes the text using stylometric heuristics.
    Returns a score between 0.0 (high variance/human) and 1.0 (low variance/AI).
    """
    if not text.strip():
        return 0.5
        
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    
    if not sentences:
        return 0.5
        
    # 1. Sentence length variance
    sentence_lengths = [len(s.split()) for s in sentences]
    mean_length = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((l - mean_length) ** 2 for l in sentence_lengths) / len(sentence_lengths)
    
    # Cap variance to normalize between 0 and 1
    # AI tends to have variance < 10. Human often > 20.
    # High variance -> lower AI score.
    max_variance = 50.0
    norm_variance = min(variance / max_variance, 1.0)
    variance_ai_score = 1.0 - norm_variance
    
    # 2. Type-token ratio (Vocabulary diversity)
    words = re.findall(r'\b\w+\b', text.lower())
    if not words:
        return 0.5
    unique_words = set(words)
    ttr = len(unique_words) / len(words)
    
    # TTR > 0.6 is typical for human short text. AI often < 0.5.
    # Higher TTR -> lower AI score
    ttr_ai_score = 1.0 - ttr
    
    # Combine the heuristics
    heuristic_score = (variance_ai_score + ttr_ai_score) / 2.0
    return min(max(heuristic_score, 0.0), 1.0)

def calculate_confidence(groq_score: float, stylo_score: float) -> float:
    """
    Combines both signals into a single confidence score.
    """
    return (groq_score + stylo_score) / 2.0
